substitutions:
  _SERVICE_NAME: 'roulet-s-law-book-icearth-platform'
  _REGION: 'us-east1'

steps:
  # Deploy to Cloud Run directly from source repository
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--source=.'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--quiet'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY




